config/routes.rb
Commentsapp::Application.routes.draw do
  

  resources :stocks
  match '/list',    to: 'stocks#list'

  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  match '/faq',    to: 'static_pages#faq'
  match '/signup', to: 'static_pages#signup'

  get "static_pages/home"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"

match "portfolios" => 'portfolios#index', :defaults => { :id => 1 }

  authenticated :user do
   root :to => 'users#show'
  end

  root :to => "static_pages#home"

  devise_for :users, :path => 'accounts' do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, path: '' do
    resources :portfolios
  end 

  scope ':user_id' do
    resources :portfolios
  end

  resources :trades do
    resources :remarks
  end  

  resources :portfolios do
    resources :trades
  end  

  resources :comments

  

  

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :capital, :name, :brokerage, :taxslipage, :totalextraround, :mriskstock, :mriskcapital, :mcats

  has_many :trades
  belongs_to :user

  def invested
  	sum = nil
  	 trades.all.each do |t|
  	 	sum = t.amount.to_f + sum.to_f	 	
  	 end	
  	sum
  end

  def current_port_value
  	sum = nil
  		trades.all.each do |t|
  			sum = t.last_amount.to_f + sum.to_f
  		end
  	sum		
  end

  def port_profit_loss
  	current_port_value.to_f - invested.to_f  	
  end 

  
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  load_and_authorize_resource :user
  load_and_authorize_resource :portfolio, :through => :user

  # GET /portfolios
  # GET /portfolios.json
  def index

    # @user = User.find(params[:user_id])
    @user = current_user
    # @user = User.find(params[:id] == -1 ? current_user_id : params[:id])
    @portfolios = @user.portfolios.all
    @portfolio_new = @user.portfolios.new
    unless @portfolios.first == nil
      @portfolio = @portfolios.first  

        unless @portfolio.trades.all.empty?
          @trades = @portfolio.trades.all  
        end
    end


    
    
    # authorize! :read, @portfolios
    

    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    # @user = User.find(params[:user_id])
    @user = current_user
    @user.id = current_user.id
    @portfolio = @user.portfolios.find(params[:id])
    @trades = @portfolio.trades.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio }
      format.js
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    # @user = User.find(params[:user_id])
    @user = current_user
    @portfolio_new = @user.portfolios.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio }
      format.js
    end
  end

  # GET /portfolios/1/edit
  def edit
    @user = User.find(params[:user_id])
    @portfolio = @user.portfolios.find(params[:id])
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @user = User.find(params[:user_id])
    @portfolio = @user.portfolios.new(params[:portfolio])
    @portfolio.capital = 1000000
    @portfolio.brokerage = 0.5
    @portfolio.taxslipage = 0.25
    @portfolio.totalextraround = 1.5
    @portfolio.mriskstock = 10
    @portfolio.mriskcapital = 1
    @portfolio.mcats = 10

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to user_portfolios_path(@user), notice: 'Portfolio was successfully created.' }
        format.json { render json: @portfolio, status: :created, location: user_portfolio_path(@user, @portfolio) }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @user = User.find(params[:user_id])
    @portfolio = @user.portfolios.find(params[:id])

    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to user_portfolios_path(@user), notice: 'Portfolio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @user = User.find(params[:user_id])
    @portfolio = @user.portfolios.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to user_portfolios_url(@user) }
      format.json { head :no_content }
    end
  end

  def new_view
    respond_to do |format|               
      format.js
    end  
  end



end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<div class="home-signup">
  <div class="home-signin-box">
    <%= form_for([@user, @portfolio], html: {class: "form-horizontal"}) do |f| %>


      <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>
    <fieldset>

      <legend>Settings of Portfolio  "<%= @portfolio.name.capitalize  %>" </legend>

      
      <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name,class: "input-xlarge" %>
  </div>
    
  </div>
  <!-- Capital -->
  <div class="control-group">
    <%= f.label :capital, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :capital, placeholder: "1000000", class: "input-xlarge" %>
    </div>
    
  </div>
<!-- Brokerage -->
  <div class="control-group">
    <%= f.label :brokerage,"Brokerage (%)", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :brokerage, placeholder: "0.5", class: "input-xlarge" %>      
    </div>
  </div>

<!--  -->
  <div class="control-group">
    <%= f.label :taxslipage, 'Tax + Slipage (%)', class: "control-label" %>
    <div class="controls">
      <%= f.text_field :taxslipage,placeholder: "0.25",  class: "input-xlarge" %>
    </div> 
  </div>

  <div class="control-group">
    <%= f.label :totalextraround, 'Total Extra on round trip (%)', class: "control-label" %>
    <div class="controls">
     <%= f.text_field :totalextraround,placeholder: "1.5",  class: "input-xlarge" %>     
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mriskstock, 'Max risk on Stock (%)', class: "control-label" %>
    <div class="controls">
      <%= f.text_field :mriskstock,placeholder: "10",  class: "input-xlarge" %>      
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mriskcapitals, 'Max risk on Capital (%)', class: "control-label" %>
    <div class="controls">
       <%= f.text_field :mriskcapital,placeholder: "1",  class: "input-xlarge" %>     
    </div>

  </div>

  <div class="control-group">
    <%= f.label :mcats, 'Max Capital Allocated to Stock (%)', class: "control-label" %>
    <div class="controls">
     <%= f.text_field :mcats,placeholder: "10",  class: "input-xlarge" %>     
    </div>

  </div>




  <div class="control-group">
    <div class="controls">
      <%= f.submit "Update Portfolio", class: "btn btn-success" %>
    </div>
    
  </div>
  <span class="btn" id="hide">Hide</span>



    </fieldset>
    <% end %>
  </div>
</div>

app/views/portfolios/_form_new.html.erb

<div class="home-signup">
  <div class="home-signin-box">
    <%= form_for([@user, @portfolio], html: {class: "form-horizontal"}) do |f| %>


      <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


<%= link_to 'Back', portfolios_path %>
    <fieldset>

      <legend>New Portfolio </legend>

      
      <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name,class: "input-xlarge" %>
  </div>
    
  </div>
  <!-- Capital -->
  <div class="control-group">
    <%= f.label :capital, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :capital, placeholder: "1000000", class: "input-xlarge" %>
    </div>
    
  </div>
<!-- Brokerage -->
  <div class="control-group">
    <%= f.label :brokerage,"Brokerage (%)", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :brokerage, placeholder: "0.5", class: "input-xlarge" %>      
    </div>
  </div>

<!--  -->
  <div class="control-group">
    <%= f.label :taxslipage, 'Tax + Slipage (%)', class: "control-label" %>
    <div class="controls">
      <%= f.text_field :taxslipage,placeholder: "0.25",  class: "input-xlarge" %>
    </div> 
  </div>

  <div class="control-group">
    <%= f.label :totalextraround, 'Total Extra on round trip (%)', class: "control-label" %>
    <div class="controls">
     <%= f.text_field :totalextraround,placeholder: "1.5",  class: "input-xlarge" %>     
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mriskstock, 'Max risk on Stock (%)', class: "control-label" %>
    <div class="controls">
      <%= f.text_field :mriskstock,placeholder: "10",  class: "input-xlarge" %>      
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mriskcapitals, 'Max risk on Capital (%)', class: "control-label" %>
    <div class="controls">
       <%= f.text_field :mriskcapital,placeholder: "1",  class: "input-xlarge" %>     
    </div>

  </div>

  <div class="control-group">
    <%= f.label :mcats, 'Max Capital Allocated to Stock (%)', class: "control-label" %>
    <div class="controls">
     <%= f.text_field :mcats,placeholder: "10",  class: "input-xlarge" %>     
    </div>

  </div>




  <div class="control-group">
    <div class="controls">
      <%= f.submit "Create Portfolio", class: "btn btn-success" %>
    </div>
    
  </div>
  <span class="btn" id="hide">Hide</span>



    </fieldset>
    <% end %>
  </div>
</div>

app/views/portfolios/_form_new_2.html.erb
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">New Portfolio</h4>
      </div>
      <div class="modal-body">

                    <%= form_for([@user, @portfolio_new], html: {class: "form-horizontal"}) do |f| %>

                    <% unless @portfolios.first.nil? %>
                                           <% if @portfolio.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

                      <ul>
                      <% @portfolio.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>
                    <% end %>

                  



                    <fieldset>



                      
                      <div class="control-group">
                    <%= f.label :name, class: "control-label" %>
                    <div class="controls">
                      <%= f.text_field :name,class: "input-xlarge" %>
                  </div>
                    
                  </div>
                  <!-- Capital -->
                  <div class="control-group">
                    <%= f.label :capital, class: "control-label" %>
                    <div class="controls">
                      <%= f.text_field :capital, placeholder: "1000000", class: "input-xlarge" %>
                    </div>
                    
                  </div>
                <!-- Brokerage -->
                  <div class="control-group">
                    <%= f.label :brokerage,"Brokerage (%)", class: "control-label" %>
                    <div class="controls">
                      <%= f.text_field :brokerage, placeholder: "0.5", class: "input-xlarge" %>      
                    </div>
                  </div>

                <!--  -->
                  <div class="control-group">
                    <%= f.label :taxslipage, 'Tax + Slipage (%)', class: "control-label" %>
                    <div class="controls">
                      <%= f.text_field :taxslipage,placeholder: "0.25",  class: "input-xlarge" %>
                    </div> 
                  </div>

                  <div class="control-group">
                    <%= f.label :totalextraround, 'Total Extra on round trip (%)', class: "control-label" %>
                    <div class="controls">
                     <%= f.text_field :totalextraround,placeholder: "1.5",  class: "input-xlarge" %>     
                    </div>
                  </div>

                  <div class="control-group">
                    <%= f.label :mriskstock, 'Max risk on Stock (%)', class: "control-label" %>
                    <div class="controls">
                      <%= f.text_field :mriskstock,placeholder: "10",  class: "input-xlarge" %>      
                    </div>
                  </div>

                  <div class="control-group">
                    <%= f.label :mriskcapitals, 'Max risk on Capital (%)', class: "control-label" %>
                    <div class="controls">
                       <%= f.text_field :mriskcapital,placeholder: "1",  class: "input-xlarge" %>     
                    </div>

                  </div>

                  <div class="control-group">
                    <%= f.label :mcats, 'Max Capital Allocated to Stock (%)', class: "control-label" %>
                    <div class="controls">
                     <%= f.text_field :mcats,placeholder: "10",  class: "input-xlarge" %>     
                    </div>

                  </div>
                    </fieldset>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        <%= f.submit "Create Portfolio", class: "btn btn-success", id: "newportsubmitbtn" %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->






app/views/portfolios/_show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Capital</th>
    <th>Invested</th>
    <th>Current Value</th>
    <th>Profit/loss</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


  <tr>
    <td><%= @portfolio.name %></td>
    <td><%= @portfolio.capital %></td>

    <td><%= number_with_precision(@portfolio.invested)  %></td>
    <td><%= number_with_precision(@portfolio.current_port_value) %></td>
    <td><%= number_with_precision(@portfolio.port_profit_loss) %></td>
    <!-- <td class="btn"><%#= link_to 'Show', @portfolio, remote: true %></td> -->
    
    <!-- <td class="btn"><%#= link_to 'Edit', edit_portfolio_path(@portfolio) %></td> -->
    
  </tr>

</table>
                          <% if false %>
                              <span class="btn"><%= link_to 'Trades', portfolio_trades_path(@portfolio), remote: true %></span>  
                          <% end %>

<span class="btn"><%= link_to 'New Trade', new_portfolio_trade_path(@portfolio), id: "newtradelink"  %></span>



<span class="btn"><%= link_to 'Settings', edit_user_portfolio_path(@user, @portfolio) %></span>
<!-- <span class="btn"><%#= link_to 'Back', portfolios_path %></span> -->
<span class="btn"><%= link_to 'Destroy', user_portfolio_path(@user, @portfolio), method: :delete, data: { confirm: 'Are you sure?' } %></span>
<span class="btn" id="hide1">Hide</span>

<br><br>

<div class="well" id="showtrades">
  <%= render "trades/trades" %>
</div>



<%= link_to 'Click Me', edit_user_portfolio_path(@user, @portfolio), data: { toggle: 'modal', target: '#modal'}  %>
<a data-toggle="modal" href="#{edit_user_portfolio_path(@user, @portfolio)}" data-target="#modal">Click me</a>

app/views/portfolios/edit.html.erb
<%= render 'form' %>

app/views/portfolios/index.html.erb
<div class="row-fluid">
    <div class="span12 well">
        <ul class="inline portinline">
            <!-- listing all the portfolios -->
           <% @portfolios.each do |portfolio| %>                     
            <!--  show portfolio button -->
            <li class="btn"><%= link_to "#{portfolio.name}", user_portfolio_path(@user, portfolio), remote: true %></li>                         
           <% end %>
        </ul>
<!-- 
        <span class="btn newportbtn"><%= link_to 'New Portfolio', new_user_portfolio_path, id: "new_portfolio", remote: true %></span> -->
        <span><button class="btn btn-primary newportbtn" type="button" data-toggle="modal" data-target="#newPortForm">New Portfolio</button> </span>
</div>


<% unless @portfolios.first.nil? %>
    <div class="well" id="showportfolio" >
        <%= render "portfolios/show" %> 
    </div>       
<% end %>
    
    
<!-- <div class="btn" id="newtradebutton">show new trade form</div> -->
<div class="well" id="newtrade" style="display: none;"></div>
<!-- <div class="btn" id="showtradesbutton">show trades</div><p id="loading">Loading..</p> -->



        <!-- New Portfolio Form Modal -->
        <div class="modal fade" id="newPortForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <%= render 'form_new_2'  %>
        </div>


</div>

app/views/portfolios/new.html.erb
<%= render 'form_new' %>

app/views/portfolios/new.js.erb
// $('#new_portfolio a').hide();
$("#newportfolioform").slideDown();
$("#newportfolioform").html("<%= j (render("form")) %>");

app/views/portfolios/new_view.html.erb
<div id="content1"></div>

app/views/portfolios/new_view.js.erb
        // $('#content1').html('<%= escape_javascript(render 'layouts/footer');

app/views/portfolios/show.html.erb
<%= render "show" %>

app/views/portfolios/show.js.erb
$("#showportfolio").slideDown();
$("#showportfolio").html("<%= j (render("show")) %>");

