config/routes.rb
Commentsapp::Application.routes.draw do
  

  resources :stocks
  match '/list',    to: 'stocks#list'

  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  match '/faq',    to: 'static_pages#faq'
  match '/signup', to: 'static_pages#signup'

  get "static_pages/home"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"

match "portfolios" => 'portfolios#index', :defaults => { :id => 1 }

  authenticated :user do
   root :to => 'users#show'
  end

  root :to => "static_pages#home"

  devise_for :users, :path => 'accounts' do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, path: '' do
    resources :portfolios
  end 

  scope ':user_id' do
    resources :portfolios
  end

  resources :trades do
    resources :remarks
  end  

  resources :portfolios do
    resources :trades
  end  

  resources :comments

  

  

end

app/models/remark.rb
class Remark < ActiveRecord::Base
  attr_accessible :cp, :date, :day_profit, :op, :remark

  belongs_to :trade
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController

  before_filter :load_trade

  # GET /remarks
  # GET /remarks.json
  def index
    # @remarks = Remark.all
    @remarks = @trade.remarks.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @remarks }
      format.js
    end
  end

  # GET /remarks/1
  # GET /remarks/1.json
  def show
    # @remark = Remark.find(params[:id])
    @trade = Trade.find(params[:trade_id])
    @remark = @trade.remarks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @remark }
    end
  end

  # GET /remarks/new
  # GET /remarks/new.json
  def new
    # @remark = Remark.new
    @remark = @trade.remarks.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @remark }
    end
  end

  # GET /remarks/1/edit
  def edit
    @trade = Trade.find(params[:trade_id])
    @remark = @trade.remarks.find(params[:id])
  end

  # POST /remarks
  # POST /remarks.json
  def create
    
    @trade = Trade.find(params[:trade_id])
    @remark = @trade.remarks.new(params[:remark])

    respond_to do |format|
      if @remark.save
        format.html { redirect_to [@trade, @remark], notice: 'Remark was successfully created.' }
        format.json { render json: @remark, status: :created, location: @remark }
      else
        format.html { render action: "new" }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /remarks/1
  # PUT /remarks/1.json
  def update
    

    @remark = @trade.remarks.find(params[:id])

    respond_to do |format|
      if @remark.update_attributes(params[:remark])
        format.html { redirect_to [@trade, @remark], notice: 'Remark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remarks/1
  # DELETE /remarks/1.json
  def destroy
    
    @remark = @trade.remarks.find(params[:id])
    @remark.destroy

    respond_to do |format|
      format.html { redirect_to trade_remarks_path(@trade) }
      format.json { head :no_content }
    end
  end
end


private
  
  def load_trade
    @trade = Trade.find(params[:trade_id])
  end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/views/remarks/_form.html.erb
<%= form_for([@trade, @remark]) do |f| %>
  <% if @remark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@remark.errors.count, "error") %> prohibited this remark from being saved:</h2>

      <ul>
      <% @remark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :op %><br />
    <%= f.text_field :op %>
  </div>
  <div class="field">
    <%= f.label :cp %><br />
    <%= f.text_field :cp %>
  </div>
  <div class="field">
    <%= f.label :day_profit %><br />
    <%= f.text_field :day_profit %>
  </div>
  <div class="field">
    <%= f.label :remark %><br />
    <%= f.text_field :remark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/remarks/_remarks.html.erb
<h1>Listing remarks</h1>
<%= @remarks.first.trade.stock %>

<table>
  <tr>
    <th>Date</th>
    <th>Op</th>
    <th>Cp</th>
    <th>Day profit</th>
    <th>Remark</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @remarks.each do |remark| %>
    
  <tr>
    <%# Time.zone = 'New Delhi' %>
    <td><%= remark.date.to_formatted_s(:short)%></td>
    <td><%= remark.op %></td>
    <td><%= remark.cp %></td>
    <td><%= remark.day_profit %></td>
    <td><%= remark.remark %></td>
     <td><%= link_to 'Show', trade_remark_path(@trade, remark) %></td> 
     <td><%= link_to 'Edit', edit_trade_remark_path(@trade, remark) %></td> 
     <td><%= link_to 'Destroy', [@trade, remark], method: :delete, data: { confirm: 'Are you sure?' } %></td> 
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Remark', new_trade_remark_path(@trade) %>
<% if @remarks.last.present? %>
<%= @remarks.last.date.to_formatted_s(:short) %>
<% end %>
<span class="btn" id="hide1">Hide</span>


app/views/remarks/edit.html.erb
<h1>Editing remark</h1>

<%= render 'form' %>

app/views/remarks/index.html.erb
<%= render 'remarks' %>

app/views/remarks/index.js.erb
// $("#showremark").slideDown();
// $("#showremark").html("<%= j (render("remarks")) %>");

// $(this).parent().parent().next().hide();
// $("#remark_<%= @remarks.first.trade.id %>").hide();
$("#remark_<%= @remarks.first.trade.id %>").slideDown().html("<%= j (render("remarks")) %>");


// $(this).hide();






app/views/remarks/new.html.erb
<h1>New remark</h1>

<%= render 'form' %>

app/views/remarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @remark.date %>
</p>

<p>
  <b>Op:</b>
  <%= @remark.op %>
</p>

<p>
  <b>Cp:</b>
  <%= @remark.cp %>
</p>

<p>
  <b>Day profit:</b>
  <%= @remark.day_profit %>
</p>

<p>
  <b>Remark:</b>
  <%= @remark.remark %>
</p>



<%= link_to 'Edit', edit_trade_remark_path(@trade, @remark) %> |
<%= link_to 'Back', trade_remarks_path(@trade) %>