config/routes.rb
Commentsapp::Application.routes.draw do
  

  resources :stocks
  match '/list',    to: 'stocks#list'

  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  match '/faq',    to: 'static_pages#faq'
  match '/signup', to: 'static_pages#signup'

  get "static_pages/home"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"

match "portfolios" => 'portfolios#index', :defaults => { :id => 1 }

  authenticated :user do
   root :to => 'users#show'
  end

  root :to => "static_pages#home"

  devise_for :users, :path => 'accounts' do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, path: '' do
    resources :portfolios
  end 

  scope ':user_id' do
    resources :portfolios
  end

  resources :trades do
    resources :remarks
  end  

  resources :portfolios do
    resources :trades
  end  

  resources :comments

  

  

end

app/models/trade.rb
class Trade < ActiveRecord::Base
  attr_accessible :bepoint, :buy_date, :buy_price, :qty, :stock

  has_many :remarks
  belongs_to :portfolio

  def amount
  	qty.to_f*buy_price.to_f
  end

  def tbr
    # sprintf "%.2f", 
    amount*portfolio.brokerage.to_f/100
    
  end

  def tamount
    amount + tbr
  end

  def minstoploss
    buy_price.to_f - (portfolio.mriskstock/100)*buy_price.to_f
  end

  def be_point
    buy_price.to_f + (portfolio.totalextraround/100)*buy_price.to_f
  end

  def totalpl
  	last_amount.to_f - amount.to_f
  end

  def iqty
    (portfolio.capital.to_f)*(portfolio.mriskcapital.to_f)/100/buy_price.to_f
  end

  def risk

    if bepoint.nil?
      (be_point - minstoploss)*qty
    else
      (be_point - bepoint.to_f)*qty
    end    
  end

  def riskperstock
    risk.to_f/tamount.to_f*100  
  end

  def riskperport
    risk.to_f/portfolio.capital.to_f*100
  end



  def last_price
  	# StockQuote::Stock.quote("#{self.stock}")[0].to_f
   
    # MarketBeat.last_trade_real_time "#{self.stock}".to_sym


    begin
      a = Nse1::Stock.new(self.stock)
      return a.last
    rescue
      return "0.00"
    end

  end

  def last_amount
  	last_price.to_i*qty.to_f
  end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  # GET /trades
  # GET /trades.json
  load_and_authorize_resource :portfolio
  load_and_authorize_resource :trade, :through => :portfolio
 
  def index
    # @trades = Trade.all
    @portfolio = Portfolio.find(params[:portfolio_id])
    @trades = @portfolio.trades.all
   


     # symbol = "LSE.L"
     # @quote = YahooFinance::get_quotes(YahooFinance::StandardQuote, symbol)[symbol]

    # @data = YahooFinance.quotes(["BVSP", "USDJPY=X"], [:ask, :bid, :last_trade_date])



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
      format.js
    end
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @portfolio = Portfolio.find(params[:portfolio_id])
    @trade = @portfolio.trades.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trade }
      format.js
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @portfolio = Portfolio.find(params[:portfolio_id])
    @trade = @portfolio.trades.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trade }
      format.js
    end
  end

  # GET /trades/1/edit
  def edit
    @portfolio = Portfolio.find(params[:portfolio_id])
    @trade = @portfolio.trades.find(params[:id])
  end

  # POST /trades
  # POST /trades.json
  def create
    @portfolio = Portfolio.find(params[:portfolio_id])
    @trade = @portfolio.trades.new(params[:trade])
    # @stock2 = StockQuote::Stock.quote("#{params[:trade][:stock]}")
    
    buy_date_formatted = DateTime.strptime(params[:trade][:buy_date], "%d/%m/%Y").to_date
    @trade.buy_date = buy_date_formatted
    
    respond_to do |format|
      if @trade.save
        format.html { redirect_to [@portfolio, @trade], notice: 'Trade was successfully created.' }
        format.json { render json: @trade, status: :created, location: @trade }
      else
        format.html { render action: "new" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @portfolio = Portfolio.find(params[:portfolio_id])
    @trade = @portfolio.trades.find(params[:id])

    # @trade = Trade.new(params[:trade])
    @trade.assign_attributes(params[:trade])
    # @stock2 = StockQuote::Stock.quote("#{params[:trade][:stock]}")
    # @trade.buy_price = @stock2.last

    respond_to do |format|
      # if @trade.update_attributes(params[:trade])
      if @trade.save
        format.html { redirect_to [@portfolio, @trade], notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @portfolio = Portfolio.find(params[:portfolio_id])
    @trade = @portfolio.trades.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_trades_url(@portfolio) }
      format.json { head :no_content }
    end
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.erb
                <script>
  $(function() {
    $( "#stockinput" ).autocomplete(
    { 
      minLength: 2,
      focus: function( event, ui ) {
            $( "#stockinput" ).val( ui.item.value );
            return false;
          },
       source:"/list.json"
    }).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
          return $( "<li>" )
           .append( "<a>" + item.label + "<br>" + item.value + "</a>" )
            .appendTo( ul );
          };
  });
</script>

<div class="home-signup">
  <div class="home-signin-box">
    <%= form_for([@portfolio, @trade], html: {class: "form-horizontal"}) do |f| %>

      <% if @trade.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

          <ul>
          <% @trade.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
     <% end %>

<span class="btn" id="hide">Hide</span>
     <fieldset>
      
       <legend> New Trade!!</legend>

       <div class="control-group">
         <%= f.label :stock, class: "control-label" %>
         <div class="controls">
           <%= f.text_field :stock, class: "input-xlarge", id: "stockinput" %>
         </div>
       </div>


       <div class="control-group">
         <%= f.label :qty, class: "control-label" %>
         <div class="controls">
           <%= f.text_field :qty, class: "input-xlarge" %>
         </div>
       </div>


       <div class="control-group">
         <%= f.label :buy_price, class: "control-label" %>
         <div class="controls">
           <%= f.text_field :buy_price, class: "input-xlarge" %>
         </div>
       </div>


       <div class="control-group">
         <%= f.label :buy_date, class: "control-label" %>
         <div class="controls input-append date">
           <%= f.text_field :buy_date,class: "span3",id: "datepicker" %><span class="add-on"><i class="icon-th"></i></span>
         </div>
       </div>


       <div class="control-group">
         <%= f.label :bepoint,'Stop Loss', class: "control-label" %>
         <div class="controls">
           <%= f.text_field :bepoint, class: "input-xlarge" %>
         </div>
       </div>

       <div class="control-group">        
         <div class="controls">
           <%= f.submit "Submit" ,class: "btn btn-success"  %>
         </div>
       </div>



     </fieldset>


    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('[data-behaviour~=datepicker]').datepicker();
</script>

app/views/trades/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stock:</b>
  <%= @trade.stock %>
</p>

<p>
  <b>Qty:</b>
  <%= @trade.qty %>
</p>

<p>
  <b>Buy price:</b>
  <%= @trade.buy_price %>
</p>

<p>
  <b>Buy date:</b>
  <%= @trade.buy_date %>
</p>

<p>
  <b>Bepoint:</b>
  <%= @trade.bepoint %>
</p>


<%= link_to 'Edit', edit_portfolio_trade_path(@portfolio, @trade) %> |
<%= link_to 'Back', portfolio_trades_path(@portfolio) %>
<span class="btn" id="hide1">Hide</span>

app/views/trades/_trades.html.erb


<!-- <h1>Listing trades (<%= @portfolio.name %>)</h1> -->
        
<% unless @portfolio.trades.all.empty? %>
        <table class="tradetable">
  <tr>
    <!-- <th>Portfolio</th> -->
    <th>Buy date</th>
    <th>Script</th>
    <th>Qty</th>
    <th>Buy price</th>
    <th>Stop Loss</th>
    <th>Last Price</th>
    <th>Amount Invested</th>
    <th>Total Brokerage</th>
    <th>Total Amount</th>
    <th>Last Amount</th>
    <th>Min StopLoss</th>
    <th>Bepoint</th>
    <th>Ideal Quantity</th>
    <div>            
        <th>Risk</th>
        <th> Risk % Stock</th>
        <th> Risk % Portfolio</th>
        <th>Profit/Loss</th>
    </div>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trades.each do |trade| %>
    <div>
      <tr >
        <% Time.zone = 'New Delhi' %>
            <% javascript_tag do %>
                <!-- document.location = '<%= url_for(trade_remarks_path(trade))%>' -->
                window.tradeid ='raw <%= trade.id.to_json %>'

            <% end %>

                   
        <!-- <td> <%#= trade.portfolio.name %></td> -->     <!-- Portfolio --> 
            <% unless trade.buy_date.nil? %>
        <td><%= trade.buy_date.to_formatted_s(:short) %></td>
            <% else %>
        <td>No date</td>       
             <% end %> 
          <!-- buy date -->
        <td><%= trade.stock %></td>  <!-- Script -->
        <td><%= trade.qty %></td> <!-- qty -->
        <td><%= trade.buy_price %></td>  <!-- buy price -->
        <td><%= trade.bepoint %></td> <!-- Stip Loss -->
        <td><%= trade.last_price %></td> <!-- last price -->
        <td><%= number_with_precision(trade.amount) %></td> <!-- amount invested -->
        <td><%= number_with_precision(trade.tbr) %></td>   <!-- total brokerage -->
        <td><%= number_with_precision(trade.tamount) %></td> <!-- total amount -->
        <td><%= number_with_precision(trade.last_amount) %></td> <!-- last amount -->
        <td><%= number_with_precision(trade.minstoploss) %></td> <!-- min Stoploss -->
        <td><%= number_with_precision(trade.be_point) %></td>  <!-- be point -->
        <td><%= number_with_precision(trade.iqty) %></td>
        <div>           
            <td><%= number_with_precision(trade.risk) %></td>
            <td><%= number_with_precision(trade.riskperstock) %></td>
            <td><%= number_with_precision(trade.riskperport) %></td>
            <td><%= number_with_precision(trade.totalpl) %></td> <!-- p/l -->
        </div>
        <td><%= link_to 'Show', portfolio_trade_path(@portfolio, trade), id: "showtradelink" %></td>
        <td><%= link_to 'Remarks', trade_remarks_path(trade), id: "showremarklink" %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', [@portfolio, trade], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr >
        <td colspan="8" rowspan="" headers="" >
            <div class="well" id="remark_<%= trade.id %>" style="display: none;">
                hello
            </div>
        </td>
      </tr>
    </div>  
<% end %>
</table>
<% else %>
    <h3>Make a new trade!!</h3>
<% end %>



<br />
                    <% if false %>
                        <span class="btn"><%= link_to 'New Trade', new_portfolio_trade_path(@portfolio), id: "newtradelink"  %></span>                
                    <% end %>
        
<span class="btn" id="hide1">Hide</span>


<div class="well" id="newtradeform" style="display: none;"></div>
<div class="well" id="showtrade" style="display: none;"></div>
<div class="well" id="showremark" style="display: none;">hi</div>

<!-- Ranodm Examples -->
    <% if false %>
                <% Time.zone = 'New Delhi' %>
            <p><%= Date.current.to_formatted_s(:short) %> </p>
            <p><%= Time.current.to_formatted_s(:short) %> </p>

    <% end %>


    
  







app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>All Trades</h1>
<%= render 'trades' %>

app/views/trades/index.js.erb

	$("#showtrades").slideDown().html("<%= j (render("trades")) %>");



app/views/trades/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', portfolio_trades_path(@portfolio) %>

app/views/trades/new.js.erb
$("#newtradeform").slideDown();
$("#newtradeform").html("<%= j (render("form")) %>");


app/views/trades/show.html.erb
<%= render 'show' %>

app/views/trades/show.js.erb
$("#showtrade").slideDown();
$("#showtrade").html("<%= j (render("show")) %>");