config/routes.rb
Commentsapp::Application.routes.draw do
  

  resources :stocks
  match '/list',    to: 'stocks#list'

  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  match '/faq',    to: 'static_pages#faq'
  match '/signup', to: 'static_pages#signup'

  get "static_pages/home"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"

match "portfolios" => 'portfolios#index', :defaults => { :id => 1 }

  authenticated :user do
   root :to => 'users#show'
  end

  root :to => "static_pages#home"

  devise_for :users, :path => 'accounts' do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, path: '' do
    resources :portfolios
  end 

  scope ':user_id' do
    resources :portfolios
  end

  resources :trades do
    resources :remarks
  end  

  resources :portfolios do
    resources :trades
  end  

  resources :comments

  

  

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-pull-bottom">
  <small>
    <a href="#">Tradeoo.in</a>
  </small>
  <nav>
    <ul class="">
      <li id="about"><%= link_to "About", about_path %></li>
      <li id="contact"><%= link_to "Contact", contact_path %></li>
      <li id="faq"><%= link_to "FAQ", faq_path %></li>
    </ul>
  </nav>
	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to image_tag("logo.png", size: "200x100", alt: "Tradeoo.in"), root_path, id: "logo", class: "brand" %>
			<nav>
				<ul class="nav pull-right">

				   <% if user_signed_in? %>

					<li><%= link_to "#{current_user.email}", '#' %></li>
					<li><%= link_to 'Portfolios', user_portfolios_path(current_user) %></li>
					<li><%= link_to 'Settings', edit_user_registration_path %></li>
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
			 	   <% else %>
					<li><%= link_to 'Login', new_user_session_path %></li>
					<li><%= link_to 'Sign Up', new_user_registration_path %></li>
				   <% end %>
				</ul>
			</nav>			
		</div>
	</div>

	
</header><!-- /header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tradeoo.in</title>
  <%= include_gon %>
  <%= stylesheet_link_tag  "jquery-ui-1.10.3.custom.css", "application", :media => "all" %>

  <%= javascript_include_tag "jquery-1.9.1.js","jquery-ui-1.10.3.custom.min.js" %>

  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="container">
	    <%= render 'layouts/header' %>

      
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>


       
      <div id="pagecontent">
         <%= yield %>
      </div>  
    </div>


    <div id="footer">
        <%= render 'layouts/footer' %>  
    </div>
      
    
</body>
</html>

app/views/layouts/homepagelayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tradeoo.in</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="container signupbackground homepage">
	    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <div id="pagecontent">
         <%= yield %>
      </div> 
      <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/signuplayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tradeoo.in</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="signupbackground">
	<%= yield %>
</body>
</html>